server:
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fruit?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
